name: "Terraform - Apply"
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-CD:
    runs-on: ubuntu-latest
    name: Terraform Apply
    steps:
      - name: checkout
        id: checkout_code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: 'Authenticate to Google Cloud'
        run: echo '${{ secrets.SA_KEY }}' >> sakey.json; cat sakey.json
        #run: gcloud auth activate-service-account ${{ vars.SA_EMAIL }} --key-file= ${{ secrets.SA_KEY }}
        # id: auth
        # uses: 'google-github-actions/auth@v0.4.0'
        # with:
        #   credentials_json: '${{ secrets.SA_KEY }}'

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply --auto-approve